import { createSlice, PayloadAction } from "@reduxjs/toolkit";

const initialState = {
  //const { data, isLoading } = useGetResturantItemsQuery()
  Item: [
    //=====================美式Taipei101==================
    {
      id: 1,
      name: "burger1",
      avatar: "/images/fooditem/burger.png",
      price: 300,
      resturant: "美式1",
      type: "Recommend",
      number: 0,
      takeoutfee: 40,
    },
    {
      id: 2,
      name: "burger2",
      avatar: "/images/fooditem/burger.png",
      price: 600,
      resturant: "美式1",
      type: "Recommend",
      number: 0,
      takeoutfee: 40,
    },
    {
      id: 3,
      name: "burger3",
      avatar: "/images/fooditem/burger.png",
      price: 800,
      resturant: "美式1",
      type: "Recommend",
      number: 0,
      takeoutfee: 40,
    },
    {
      id: 4,
      name: "burger4",
      avatar: "/images/fooditem/burger.png",
      price: 300,
      resturant: "美式1",
      type: "Food",
      number: 0,
      takeoutfee: 40,
    },
    {
      id: 5,
      name: "burger5",
      avatar: "/images/fooditem/burger.png",
      price: 600,
      resturant: "美式1",
      type: "Food",
      number: 0,
      takeoutfee: 40,
    },
    {
      id: 6,
      name: "burger6",
      avatar: "/images/fooditem/burger.png",
      price: 800,
      resturant: "美式1",
      type: "Food",
      number: 0,
      takeoutfee: 40,
    },
    {
      id: 7,
      name: "burger7",
      avatar: "/images/fooditem/burger.png",
      price: 1200,
      resturant: "美式1",
      type: "Food",
      number: 0,
      takeoutfee: 40,
    },
    {
      id: 8,
      name: "burger8",
      avatar: "/images/fooditem/burger.png",
      price: 300,
      resturant: "美式1",
      type: "Drink",
      number: 0,
      takeoutfee: 40,
    },
    {
      id: 9,
      name: "burger9",
      avatar: "/images/fooditem/burger.png",
      price: 600,
      resturant: "美式1",
      type: "Drink",
      number: 0,
      takeoutfee: 40,
    },
    {
      id: 10,
      name: "burger10",
      avatar: "/images/fooditem/burger.png",
      price: 800,
      resturant: "美式1",
      type: "Drink",
      number: 0,
      takeoutfee: 40,
    },
    //-----------------------------美式Taipei105-------------------------
    {
      id: 11,
      name: "burger51",
      avatar: "/images/fooditem/burger.png",
      price: 550,
      resturant: "美式5",
      type: "Recommend",
      number: 0,
      takeoutfee: 40,
    },
    {
      id: 12,
      name: "burger12",
      avatar: "/images/fooditem/burger.png",
      price: 550,
      resturant: "美式5",
      type: "Recommend",
      number: 0,
      takeoutfee: 40,
    },
    {
      id: 13,
      name: "burger13",
      avatar: "/images/fooditem/burger.png",
      price: 550,
      resturant: "美式5",
      type: "Recommend",
      number: 0,
      takeoutfee: 40,
    },
    {
      id: 14,
      name: "burger4",
      avatar: "/images/fooditem/burger.png",
      price: 550,
      resturant: "美式5",
      type: "Food",
      number: 0,
      takeoutfee: 40,
    },
    {
      id: 15,
      name: "burger5",
      avatar: "/images/fooditem/burger.png",
      price: 550,
      resturant: "美式5",
      type: "Food",
      number: 0,
      takeoutfee: 40,
    },
    {
      id: 16,
      name: "burger6",
      avatar: "/images/fooditem/burger.png",
      price: 550,
      resturant: "美式5",
      type: "Food",
      number: 0,
      takeoutfee: 40,
    },
    {
      id: 17,
      name: "burger7",
      avatar: "/images/fooditem/burger.png",
      price: 550,
      resturant: "美式5",
      type: "Food",
      number: 0,
      takeoutfee: 40,
    },
    {
      id: 18,
      name: "burger8",
      avatar: "/images/fooditem/burger.png",
      price: 550,
      resturant: "美式5",
      type: "Drink",
      number: 0,
      takeoutfee: 40,
    },
    {
      id: 19,
      name: "burger9",
      avatar: "/images/fooditem/burger.png",
      price: 550,
      resturant: "美式5",
      type: "Drink",
      number: 0,
      takeoutfee: 40,
    },
    {
      id: 20,
      name: "burger10",
      avatar: "/images/fooditem/burger.png",
      price: 550,
      resturant: "美式5",
      type: "Drink",
      number: 0,
      takeoutfee: 40,
    },
    //=====================台式Taipei104==================
    {
      id: 21,
      name: "burger41",
      avatar: "/images/fooditem/burger.png",
      price: 550,
      resturant: "台式4",
      type: "Recommend",
      number: 0,
      takeoutfee: 40,
    },
    {
      id: 22,
      name: "burger2",
      avatar: "/images/fooditem/burger.png",
      price: 550,
      resturant: "台式4",
      type: "Recommend",
      number: 0,
      takeoutfee: 40,
    },
    {
      id: 23,
      name: "burger3",
      avatar: "/images/fooditem/burger.png",
      price: 550,
      resturant: "台式4",
      type: "Recommend",
      number: 0,
      takeoutfee: 40,
    },
    {
      id: 24,
      name: "burger4",
      avatar: "/images/fooditem/burger.png",
      price: 550,
      resturant: "台式4",
      type: "Food",
      number: 0,
      takeoutfee: 40,
    },
    {
      id: 25,
      name: "burger5",
      avatar: "/images/fooditem/burger.png",
      price: 550,
      resturant: "台式4",
      type: "Food",
      number: 0,
      takeoutfee: 40,
    },
    {
      id: 26,
      name: "burger6",
      avatar: "/images/fooditem/burger.png",
      price: 550,
      resturant: "台式4",
      type: "Food",
      number: 0,
      takeoutfee: 40,
    },
    {
      id: 27,
      name: "burger7",
      avatar: "/images/fooditem/burger.png",
      price: 550,
      resturant: "台式4",
      type: "Food",
      number: 0,
      takeoutfee: 40,
    },
    {
      id: 28,
      name: "burger8",
      avatar: "/images/fooditem/burger.png",
      price: 550,
      resturant: "台式4",
      type: "Drink",
      number: 0,
      takeoutfee: 40,
    },
    {
      id: 29,
      name: "burger9",
      avatar: "/images/fooditem/burger.png",
      price: 550,
      resturant: "台式4",
      type: "Drink",
      number: 0,
      takeoutfee: 40,
    },
    {
      id: 30,
      name: "burger10",
      avatar: "/images/fooditem/burger.png",
      price: 550,
      resturant: "台式4",
      type: "Drink",
      number: 0,
      takeoutfee: 40,
    },
    //=====================台式Taipei108==================
    {
      id: 31,
      name: "burger81",
      avatar: "/images/fooditem/burger.png",
      price: 550,
      resturant: "台式8",
      type: "Recommend",
      number: 0,
      takeoutfee: 40,
    },
    {
      id: 32,
      name: "burger2",
      avatar: "/images/fooditem/burger.png",
      price: 550,
      resturant: "台式8",
      type: "Recommend",
      number: 0,
      takeoutfee: 40,
    },
    {
      id: 33,
      name: "burger3",
      avatar: "/images/fooditem/burger.png",
      price: 550,
      resturant: "台式8",
      type: "Recommend",
      number: 0,
      takeoutfee: 40,
    },
    {
      id: 34,
      name: "burger4",
      avatar: "/images/fooditem/burger.png",
      price: 550,
      resturant: "台式8",
      type: "Food",
      number: 0,
      takeoutfee: 40,
    },
    {
      id: 35,
      name: "burger5",
      avatar: "/images/fooditem/burger.png",
      price: 550,
      resturant: "台式8",
      type: "Food",
      number: 0,
      takeoutfee: 40,
    },
    {
      id: 36,
      name: "burger6",
      avatar: "/images/fooditem/burger.png",
      price: 550,
      resturant: "台式8",
      type: "Food",
      number: 0,
      takeoutfee: 40,
    },
    {
      id: 37,
      name: "burger7",
      avatar: "/images/fooditem/burger.png",
      price: 550,
      resturant: "台式8",
      type: "Food",
      number: 0,
      takeoutfee: 40,
    },
    {
      id: 38,
      name: "burger8",
      avatar: "/images/fooditem/burger.png",
      price: 550,
      resturant: "台式8",
      type: "Drink",
      number: 0,
      takeoutfee: 40,
    },
    {
      id: 39,
      name: "burger9",
      avatar: "/images/fooditem/burger.png",
      price: 550,
      resturant: "台式8",
      type: "Drink",
      number: 0,
      takeoutfee: 40,
    },
    {
      id: 40,
      name: "burger10",
      avatar: "/images/fooditem/burger.png",
      price: 550,
      resturant: "台式8",
      type: "Drink",
      number: 0,
      takeoutfee: 40,
    },
    //=====================台式Taipei109==================
    {
      id: 41,
      name: "burger91",
      avatar: "/images/fooditem/burger.png",
      price: 550,
      resturant: "台式9",
      type: "Recommend",
      number: 0,
      takeoutfee: 40,
    },
    {
      id: 42,
      name: "burger2",
      avatar: "/images/fooditem/burger.png",
      price: 550,
      resturant: "台式9",
      type: "Recommend",
      number: 0,
      takeoutfee: 40,
    },
    {
      id: 43,
      name: "burger3",
      avatar: "/images/fooditem/burger.png",
      price: 550,
      resturant: "台式9",
      type: "Recommend",
      number: 0,
      takeoutfee: 40,
    },
    {
      id: 44,
      name: "burger4",
      avatar: "/images/fooditem/burger.png",
      price: 550,
      resturant: "台式9",
      type: "Food",
      number: 0,
      takeoutfee: 40,
    },
    {
      id: 45,
      name: "burger5",
      avatar: "/images/fooditem/burger.png",
      price: 550,
      resturant: "台式9",
      type: "Food",
      number: 0,
      takeoutfee: 40,
    },
    {
      id: 46,
      name: "burger6",
      avatar: "/images/fooditem/burger.png",
      price: 550,
      resturant: "台式9",
      type: "Food",
      number: 0,
      takeoutfee: 40,
    },
    {
      id: 47,
      name: "burger7",
      avatar: "/images/fooditem/burger.png",
      price: 550,
      resturant: "台式9",
      type: "Food",
      number: 0,
      takeoutfee: 40,
    },
    {
      id: 48,
      name: "burger8",
      avatar: "/images/fooditem/burger.png",
      price: 550,
      resturant: "台式9",
      type: "Drink",
      number: 0,
      takeoutfee: 40,
    },
    {
      id: 49,
      name: "burger9",
      avatar: "/images/fooditem/burger.png",
      price: 550,
      resturant: "台式9",
      type: "Drink",
      number: 0,
      takeoutfee: 40,
    },
    {
      id: 50,
      name: "burger10",
      avatar: "/images/fooditem/burger.png",
      price: 550,
      resturant: "台式9",
      type: "Drink",
      number: 0,
      takeoutfee: 40,
    },
    //=====================歐式Taipei103==================
    {
      id: 51,
      name: "burger31",
      avatar: "/images/fooditem/burger.png",
      price: 550,
      resturant: "歐式3",
      type: "Recommend",
      number: 0,
      takeoutfee: 40,
    },
    {
      id: 52,
      name: "burger2",
      avatar: "/images/fooditem/burger.png",
      price: 550,
      resturant: "歐式3",
      type: "Recommend",
      number: 0,
      takeoutfee: 40,
    },
    {
      id: 53,
      name: "burger3",
      avatar: "/images/fooditem/burger.png",
      price: 550,
      resturant: "歐式3",
      type: "Recommend",
      number: 0,
      takeoutfee: 40,
    },
    {
      id: 54,
      name: "burger4",
      avatar: "/images/fooditem/burger.png",
      price: 550,
      resturant: "歐式3",
      type: "Food",
      number: 0,
      takeoutfee: 40,
    },
    {
      id: 55,
      name: "burger5",
      avatar: "/images/fooditem/burger.png",
      price: 550,
      resturant: "歐式3",
      type: "Food",
      number: 0,
      takeoutfee: 40,
    },
    {
      id: 56,
      name: "burger6",
      avatar: "/images/fooditem/burger.png",
      price: 550,
      resturant: "歐式3",
      type: "Food",
      number: 0,
      takeoutfee: 40,
    },
    {
      id: 57,
      name: "burger7",
      avatar: "/images/fooditem/burger.png",
      price: 550,
      resturant: "歐式3",
      type: "Food",
      number: 0,
      takeoutfee: 40,
    },
    {
      id: 58,
      name: "burger8",
      avatar: "/images/fooditem/burger.png",
      price: 550,
      resturant: "歐式3",
      type: "Drink",
      number: 0,
      takeoutfee: 40,
    },
    {
      id: 59,
      name: "burger9",
      avatar: "/images/fooditem/burger.png",
      price: 550,
      resturant: "歐式3",
      type: "Drink",
      number: 0,
      takeoutfee: 40,
    },
    {
      id: 60,
      name: "burger10",
      avatar: "/images/fooditem/burger.png",
      price: 550,
      resturant: "歐式3",
      type: "Drink",
      number: 0,
      takeoutfee: 40,
    },
    //=====================歐式Taipei106==================
    {
      id: 61,
      name: "burger61",
      avatar: "/images/fooditem/burger.png",
      price: 550,
      resturant: "歐式6",
      type: "Recommend",
      number: 0,
      takeoutfee: 40,
    },
    {
      id: 62,
      name: "burger2",
      avatar: "/images/fooditem/burger.png",
      price: 550,
      resturant: "歐式6",
      type: "Recommend",
      number: 0,
      takeoutfee: 40,
    },
    {
      id: 63,
      name: "burger3",
      avatar: "/images/fooditem/burger.png",
      price: 550,
      resturant: "歐式6",
      type: "Recommend",
      number: 0,
      takeoutfee: 40,
    },
    {
      id: 64,
      name: "burger4",
      avatar: "/images/fooditem/burger.png",
      price: 550,
      resturant: "歐式6",
      type: "Food",
      number: 0,
      takeoutfee: 40,
    },
    {
      id: 65,
      name: "burger5",
      avatar: "/images/fooditem/burger.png",
      price: 550,
      resturant: "歐式6",
      type: "Food",
      number: 0,
      takeoutfee: 40,
    },
    {
      id: 66,
      name: "burger6",
      avatar: "/images/fooditem/burger.png",
      price: 550,
      resturant: "歐式6",
      type: "Food",
      number: 0,
      takeoutfee: 40,
    },
    {
      id: 67,
      name: "burger7",
      avatar: "/images/fooditem/burger.png",
      price: 550,
      resturant: "歐式6",
      type: "Food",
      number: 0,
      takeoutfee: 40,
    },
    {
      id: 68,
      name: "burger8",
      avatar: "/images/fooditem/burger.png",
      price: 550,
      resturant: "歐式6",
      type: "Drink",
      number: 0,
      takeoutfee: 40,
    },
    {
      id: 69,
      name: "burger9",
      avatar: "/images/fooditem/burger.png",
      price: 550,
      resturant: "歐式6",
      type: "Drink",
      number: 0,
      takeoutfee: 40,
    },
    {
      id: 70,
      name: "burger10",
      avatar: "/images/fooditem/burger.png",
      price: 550,
      resturant: "歐式6",
      type: "Drink",
      number: 0,
      takeoutfee: 40,
    },
    //=====================歐式Taipei110==================
    {
      id: 71,
      name: "burger110",
      avatar: "/images/fooditem/burger.png",
      price: 550,
      resturant: "歐式10",
      type: "Recommend",
      number: 0,
      takeoutfee: 40,
    },
    {
      id: 72,
      name: "burger2",
      avatar: "/images/fooditem/burger.png",
      price: 550,
      resturant: "歐式10",
      type: "Recommend",
      number: 0,
      takeoutfee: 40,
    },
    {
      id: 73,
      name: "burger3",
      avatar: "/images/fooditem/burger.png",
      price: 550,
      resturant: "歐式10",
      type: "Recommend",
      number: 0,
      takeoutfee: 40,
    },
    {
      id: 74,
      name: "burger4",
      avatar: "/images/fooditem/burger.png",
      price: 550,
      resturant: "歐式10",
      type: "Food",
      number: 0,
      takeoutfee: 40,
    },
    {
      id: 75,
      name: "burger5",
      avatar: "/images/fooditem/burger.png",
      price: 550,
      resturant: "歐式10",
      type: "Food",
      number: 0,
      takeoutfee: 40,
    },
    {
      id: 76,
      name: "burger6",
      avatar: "/images/fooditem/burger.png",
      price: 550,
      resturant: "歐式10",
      type: "Food",
      number: 0,
      takeoutfee: 40,
    },
    {
      id: 77,
      name: "burger7",
      avatar: "/images/fooditem/burger.png",
      price: 550,
      resturant: "歐式10",
      type: "Food",
      number: 0,
      takeoutfee: 40,
    },
    {
      id: 78,
      name: "burger8",
      avatar: "/images/fooditem/burger.png",
      price: 550,
      resturant: "歐式10",
      type: "Drink",
      number: 0,
      takeoutfee: 40,
    },
    {
      id: 79,
      name: "burger9",
      avatar: "/images/fooditem/burger.png",
      price: 550,
      resturant: "歐式10",
      type: "Drink",
      number: 0,
      takeoutfee: 40,
    },
    {
      id: 80,
      name: "burger10",
      avatar: "/images/fooditem/burger.png",
      price: 550,
      resturant: "歐式10",
      type: "Drink",
      number: 0,
      takeoutfee: 40,
    },
    //=====================日式Taipei102==================
    {
      id: 81,
      name: "burger102",
      avatar: "/images/fooditem/burger.png",
      price: 550,
      resturant: "日式2",
      type: "Recommend",
      number: 0,
      takeoutfee: 40,
    },
    {
      id: 82,
      name: "burger2",
      avatar: "/images/fooditem/burger.png",
      price: 550,
      resturant: "日式2",
      type: "Recommend",
      number: 0,
      takeoutfee: 40,
    },
    {
      id: 83,
      name: "burger3",
      avatar: "/images/fooditem/burger.png",
      price: 550,
      resturant: "日式2",
      type: "Recommend",
      number: 0,
      takeoutfee: 40,
    },
    {
      id: 84,
      name: "burger4",
      avatar: "/images/fooditem/burger.png",
      price: 550,
      resturant: "日式2",
      type: "Food",
      number: 0,
      takeoutfee: 40,
    },
    {
      id: 85,
      name: "burger5",
      avatar: "/images/fooditem/burger.png",
      price: 550,
      resturant: "日式2",
      type: "Food",
      number: 0,
      takeoutfee: 40,
    },
    {
      id: 86,
      name: "burger6",
      avatar: "/images/fooditem/burger.png",
      price: 550,
      resturant: "日式2",
      type: "Food",
      number: 0,
      takeoutfee: 40,
    },
    {
      id: 87,
      name: "burger7",
      avatar: "/images/fooditem/burger.png",
      price: 550,
      resturant: "日式2",
      type: "Food",
      number: 0,
      takeoutfee: 40,
    },
    {
      id: 88,
      name: "burger8",
      avatar: "/images/fooditem/burger.png",
      price: 550,
      resturant: "日式2",
      type: "Drink",
      number: 0,
      takeoutfee: 40,
    },
    {
      id: 89,
      name: "burger9",
      avatar: "/images/fooditem/burger.png",
      price: 550,
      resturant: "日式2",
      type: "Drink",
      number: 0,
      takeoutfee: 40,
    },
    {
      id: 90,
      name: "burger10",
      avatar: "/images/fooditem/burger.png",
      price: 550,
      resturant: "日式2",
      type: "Drink",
      number: 0,
      takeoutfee: 40,
    },
    //=====================日式Taipei107==================
    {
      id: 91,
      name: "burger107",
      avatar: "/images/fooditem/burger.png",
      price: 550,
      resturant: "日式7",
      type: "Recommend",
      number: 0,
      takeoutfee: 40,
    },
    {
      id: 92,
      name: "burger2",
      avatar: "/images/fooditem/burger.png",
      price: 550,
      resturant: "日式7",
      type: "Recommend",
      number: 0,
      takeoutfee: 40,
    },
    {
      id: 93,
      name: "burger3",
      avatar: "/images/fooditem/burger.png",
      price: 550,
      resturant: "日式7",
      type: "Recommend",
      number: 0,
      takeoutfee: 40,
    },
    {
      id: 94,
      name: "burger4",
      avatar: "/images/fooditem/burger.png",
      price: 550,
      resturant: "日式7",
      type: "Food",
      number: 0,
      takeoutfee: 40,
    },
    {
      id: 95,
      name: "burger5",
      avatar: "/images/fooditem/burger.png",
      price: 550,
      resturant: "日式7",
      type: "Food",
      number: 0,
      takeoutfee: 40,
    },
    {
      id: 96,
      name: "burger6",
      avatar: "/images/fooditem/burger.png",
      price: 550,
      resturant: "日式7",
      type: "Food",
      number: 0,
      takeoutfee: 40,
    },
    {
      id: 97,
      name: "burger7",
      avatar: "/images/fooditem/burger.png",
      price: 550,
      resturant: "日式7",
      type: "Food",
      number: 0,
      takeoutfee: 40,
    },
    {
      id: 98,
      name: "burger8",
      avatar: "/images/fooditem/burger.png",
      price: 550,
      resturant: "日式7",
      type: "Drink",
      number: 0,
      takeoutfee: 40,
    },
    {
      id: 99,
      name: "burger9",
      avatar: "/images/fooditem/burger.png",
      price: 550,
      resturant: "日式7",
      type: "Drink",
      number: 0,
      takeoutfee: 40,
    },
    {
      id: 100,
      name: "burger10",
      avatar: "/images/fooditem/burger.png",
      price: 550,
      resturant: "日式7",
      type: "Drink",
      number: 0,
      takeoutfee: 40,
    },
  ],
};

export const ItemSlice = createSlice({
  name: "ItemSlice",
  initialState,
  //TODO: 這邊是reducers!!
  reducers: {
    add: (state, action) => {
      const items = state.Item;
      for (let i = 0; i < items.length; i++) {
        const item = items[i];
        //TODO: id的問題！！
        if (item.id === action.payload) {
          //   item.isFollowing = true;
          item.number += 1;
        }
      }
    },
    minus: (state, action) => {
      const items = state.Item;
      for (let i = 0; i < items.length; i++) {
        const item = items[i];
        if (item.id === action.payload) {
          //   item.isFollowing = true;
          if (item.number === 0) {
            item.number = 0;
          } else {
            item.number -= 1;
          }
        }
      }
    },
    reload: (state, action) => {
      const items = state.Item;
      for (let i = 0; i < items.length; i++) {
        const item = items[i];
        item.number = 0;
      }
    },
  },
});

export const { add, minus, reload } = ItemSlice.actions;

export default ItemSlice.reducer;
